/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    collage: Collage;
    songs: Song;
    videos: Video;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    collage: CollageSelect<false> | CollageSelect<true>;
    songs: SongsSelect<false> | SongsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'art-page': ArtPage;
    'resources-page': ResourcesPage;
    'contact-page': ContactPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'art-page': ArtPageSelect<false> | ArtPageSelect<true>;
    'resources-page': ResourcesPageSelect<false> | ResourcesPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every piece in the Collage gallery. Drag the handle on the left to change the order they appear in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collage".
 */
export interface Collage {
  id: number;
  _order?: string | null;
  /**
   * Read aloud to people using screen readers, and shown if the image can’t load. Describe what is in the picture in one sentence, e.g. “Becca smiling in a black rose-print top.”
   */
  alt: string;
  /**
   * Not shown on the site yet. Useful for finding pieces here.
   */
  title?: string | null;
  year?: number | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Songs on the Songs page. Upload an MP3, give it a title, and publish. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs".
 */
export interface Song {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Include anyone you collaborated with.
   */
  artist: string;
  /**
   * Minutes:seconds, e.g. 4:11
   */
  duration?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Videos on the Videos page. Paste a YouTube link, add a title and a line about it, and publish. Drag to reorder; the first one is shown large.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  _order?: string | null;
  /**
   * Copy the link from the Share button on YouTube.
   */
  youtubeUrl: string;
  title: string;
  description: string;
  /**
   * Shown before the video plays. Leave empty to use YouTube’s own thumbnail.
   */
  poster?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos and artwork used on the pages (portraits, the home page art, video covers). Collage pieces are added under Art → Collage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Read aloud to people using screen readers, and shown if the image can’t load. Describe what is in the picture in one sentence, e.g. “Becca smiling in a black rose-print top.”
   */
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'collage';
        value: number | Collage;
      } | null)
    | ({
        relationTo: 'songs';
        value: number | Song;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collage_select".
 */
export interface CollageSelect<T extends boolean = true> {
  _order?: T;
  alt?: T;
  title?: T;
  year?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs_select".
 */
export interface SongsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  artist?: T;
  duration?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  _order?: T;
  youtubeUrl?: T;
  title?: T;
  description?: T;
  poster?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The first page visitors see.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * A tall (portrait) image works best. The face should be in the upper half.
   */
  heroImage: number | Media;
  eyebrow?: string | null;
  primaryButton: {
    text: string;
    page: '/' | '/about-me' | '/art' | '/collage-art' | '/music' | '/videos' | '/resources' | '/contact';
  };
  secondaryButton: {
    text: string;
    page: '/' | '/about-me' | '/art' | '/collage-art' | '/music' | '/videos' | '/resources' | '/contact';
  };
  leadIn?: string | null;
  /**
   * The last line is shown bold and pink.
   */
  stanzas?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  closingLine?: string | null;
  storyPortrait: number | Media;
  storyQuote?: string | null;
  storyText?: string | null;
  storyButton: {
    text: string;
    page: '/' | '/about-me' | '/art' | '/collage-art' | '/music' | '/videos' | '/resources' | '/contact';
  };
  doorsHeading?: string | null;
  collageDoor?: string | null;
  songsDoor?: string | null;
  videosDoor?: string | null;
  closingHeading?: string | null;
  closingText?: string | null;
  /**
   * The last word is shown in italic pink.
   */
  closingWords?: string | null;
  closingButton: {
    text: string;
    page: '/' | '/about-me' | '/art' | '/collage-art' | '/music' | '/videos' | '/resources' | '/contact';
  };
  /**
   * How this page appears in Google results and when someone shares the link.
   */
  seo: {
    /**
     * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
     */
    title: string;
    /**
     * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
     */
    description: string;
    /**
     * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
     */
    shareImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Becca’s story.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Shown after the heading in light pink.
   */
  headingEmphasis?: string | null;
  lede?: string | null;
  /**
   * The last line is shown bold and pink.
   */
  affirmations?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  connectText?: string | null;
  connectLabel?: string | null;
  connectUrl?: string | null;
  portrait: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * How this page appears in Google results and when someone shares the link.
   */
  seo: {
    /**
     * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
     */
    title: string;
    /**
     * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
     */
    description: string;
    /**
     * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
     */
    shareImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Headings and intros for the Art pages. To add or change collage pieces, songs or videos, use the Art section in the menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "art-page".
 */
export interface ArtPage {
  id: number;
  art: {
    heading?: string | null;
    /**
     * How this page appears in Google results and when someone shares the link.
     */
    seo: {
      /**
       * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
       */
      title: string;
      /**
       * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
       */
      description: string;
      /**
       * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
       */
      shareImage?: (number | null) | Media;
    };
  };
  collage: {
    heading?: string | null;
    /**
     * How this page appears in Google results and when someone shares the link.
     */
    seo: {
      /**
       * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
       */
      title: string;
      /**
       * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
       */
      description: string;
      /**
       * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
       */
      shareImage?: (number | null) | Media;
    };
  };
  songs: {
    heading?: string | null;
    intro?: string | null;
    /**
     * How this page appears in Google results and when someone shares the link.
     */
    seo: {
      /**
       * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
       */
      title: string;
      /**
       * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
       */
      description: string;
      /**
       * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
       */
      shareImage?: (number | null) | Media;
    };
  };
  videos: {
    heading?: string | null;
    lede?: string | null;
    /**
     * How this page appears in Google results and when someone shares the link.
     */
    seo: {
      /**
       * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
       */
      title: string;
      /**
       * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
       */
      description: string;
      /**
       * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
       */
      shareImage?: (number | null) | Media;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Definitions, documents and helpful links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-page".
 */
export interface ResourcesPage {
  id: number;
  heading?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * How this page appears in Google results and when someone shares the link.
   */
  seo: {
    /**
     * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
     */
    title: string;
    /**
     * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
     */
    description: string;
    /**
     * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
     */
    shareImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact details and the message form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  lede?: string | null;
  about: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Each line is shown on its own line.
   */
  bookingAddress?: string | null;
  bookingHint?: string | null;
  topics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How this page appears in Google results and when someone shares the link.
   */
  seo: {
    /**
     * Shown as the blue link in Google and on the browser tab. “— Nothing Wrong With You” is added automatically.
     */
    title: string;
    /**
     * One or two sentences. Shown under the page title in Google. About 150 characters is ideal.
     */
    description: string;
    /**
     * Shown when the link is shared on social media. Leave empty to use the site-wide sharing image from Site Settings.
     */
    shareImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Things that appear on every page. Changes go live as soon as you press Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Shown under the title on the home page and in the footer.
   */
  tagline: string;
  ownerName: string;
  /**
   * Used by Google to describe the site as a whole.
   */
  defaultDescription: string;
  /**
   * Shown when a page is shared on social media, unless that page has its own. Best size: 1200 × 630.
   */
  shareImage?: (number | null) | Media;
  /**
   * Shown in the Social menu, the footer and on the Contact page. Drag to reorder.
   */
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  safety?: {
    /**
     * Shown at the top of About, Resources and Videos.
     */
    contentNote?: {
      enabled?: boolean | null;
      text?: string | null;
    };
    /**
     * Shown in the footer and on the Resources and Contact pages.
     */
    crisis?: {
      enabled?: boolean | null;
      lines?:
        | {
            name: string;
            how: string;
            /**
             * Digits only; used for tap-to-call on phones.
             */
            phone: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Shown at the bottom of every page.
     */
    legalNotice?: {
      enabled?: boolean | null;
      text?: string | null;
    };
    /**
     * A red button in the header that leaves this site immediately (also: press Esc three times). Off by default.
     */
    quickExit?: {
      enabled?: boolean | null;
      url?: string | null;
    };
  };
  contactForm?: {
    /**
     * The code after /f/ in your Formspree form’s address (e.g. for https://formspree.io/f/xyzabcd enter xyzabcd). Messages go to the email set up in Formspree. While this is empty, the form is shown but can’t be sent.
     */
    formspreeId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroImage?: T;
  eyebrow?: T;
  primaryButton?:
    | T
    | {
        text?: T;
        page?: T;
      };
  secondaryButton?:
    | T
    | {
        text?: T;
        page?: T;
      };
  leadIn?: T;
  stanzas?:
    | T
    | {
        line?: T;
        id?: T;
      };
  closingLine?: T;
  storyPortrait?: T;
  storyQuote?: T;
  storyText?: T;
  storyButton?:
    | T
    | {
        text?: T;
        page?: T;
      };
  doorsHeading?: T;
  collageDoor?: T;
  songsDoor?: T;
  videosDoor?: T;
  closingHeading?: T;
  closingText?: T;
  closingWords?: T;
  closingButton?:
    | T
    | {
        text?: T;
        page?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        shareImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingEmphasis?: T;
  lede?: T;
  affirmations?:
    | T
    | {
        line?: T;
        id?: T;
      };
  connectText?: T;
  connectLabel?: T;
  connectUrl?: T;
  portrait?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        shareImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "art-page_select".
 */
export interface ArtPageSelect<T extends boolean = true> {
  art?:
    | T
    | {
        heading?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              shareImage?: T;
            };
      };
  collage?:
    | T
    | {
        heading?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              shareImage?: T;
            };
      };
  songs?:
    | T
    | {
        heading?: T;
        intro?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              shareImage?: T;
            };
      };
  videos?:
    | T
    | {
        heading?: T;
        lede?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
              shareImage?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-page_select".
 */
export interface ResourcesPageSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        shareImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  about?: T;
  bookingAddress?: T;
  bookingHint?: T;
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        shareImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  ownerName?: T;
  defaultDescription?: T;
  shareImage?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  safety?:
    | T
    | {
        contentNote?:
          | T
          | {
              enabled?: T;
              text?: T;
            };
        crisis?:
          | T
          | {
              enabled?: T;
              lines?:
                | T
                | {
                    name?: T;
                    how?: T;
                    phone?: T;
                    id?: T;
                  };
            };
        legalNotice?:
          | T
          | {
              enabled?: T;
              text?: T;
            };
        quickExit?:
          | T
          | {
              enabled?: T;
              url?: T;
            };
      };
  contactForm?:
    | T
    | {
        formspreeId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}